### PR TITLE
replace_squaremask: `show_mask` param

### PR DESCRIPTION
**Pull request by LightArrowsEXE**
Add a `show_mask` param so users who want to use `replace_squaremask` are not forced to call `squaremask` separately just to check the mask.

### CODE REVIEW

**Comment by Setsugennoao** [comment]
1) I don't really like the idea but it's fine to add
2) Fix the conflicts
3) Fix the output length of the mask

**Comment by LightArrowsEXE** [comment]
How's this look now?

**Comment by Setsugennoao** [comment]
Can you just reassign mask and reuse it in the maskedmerge too

**Comment by LightArrowsEXE** [comment]
> Can you just reassign mask and reuse it in the maskedmerge too

Like this?

**Pull request merged**
